// Generated by CoffeeScript 1.6.1
(function() {

  window.onload = function() {
    function getMousePos(canvas, evt) {
		var rect = canvas.getBoundingClientRect();
		return {
		x: evt.clientX - rect.left,
		y: evt.clientY - rect.top
		};
	};
    var blocos, can, cont, cx, cxx, cy, cyy, d, endblocos, frame, height, i, j, particulas, passo, passoframe, posverde1, posverde2, posverde3, r, resultados, verde1, verde2, verde3, width, _i, _j, _ref, _ref1, _ref2, _ref3;
    height = 600;
    width = 1000;
    r = 75;
    cx = 500;
    cy = 300;
    d = 160;
    cxx = 375;
    cyy = 225;
    cont = 360 * 4;
    frame = 0;
    passo = 3;
    particulas = 20;
    passoframe = 3;
    posverde1 = [525.0, 225.0];
    posverde2 = [375.0, 311.6025403784439];
    posverde3 = [374.99999999999994, 138.39745962155615];
    endblocos = [];
    for (j = _i = _ref = cy - 20, _ref1 = cy - 20 + particulas; _ref <= _ref1 ? _i < _ref1 : _i > _ref1; j = _ref <= _ref1 ? ++_i : --_i) {
      for (i = _j = _ref2 = 1.3 * cx / 2, _ref3 = 1.3 * cx / 2 + particulas; _ref2 <= _ref3 ? _j < _ref3 : _j > _ref3; i = _ref2 <= _ref3 ? ++_j : --_j) {
        endblocos.push([i, j]);
      }
    }
    blocos = [];
    resultados = [];
    window.geraBlocos = function() {
      var _k, _len, _results;
      cont = 0;
      _results = [];
      for (_k = 0, _len = endblocos.length; _k < _len; _k++) {
        i = endblocos[_k];
        _results.push((function(i) {
          blocos.push(Crafty.e("bloco").attr({
            x: i[0],
            y: i[1],
            ponto: i,
            v: new Crafty.math.Vector2D(1, (cont / 400) - 0.5)
          }));
          return cont += 1;
        })(i));
      }
      return _results;
    };
    Crafty.init(width, height);
    Crafty.canvas.init(width, height);
    can = Crafty.canvas._canvas;
    Crafty.pause();
    Crafty.sprite(150, 150, "images/verde150.png", {
      verde: [0, 0]
    });
    Crafty.sprite(10, 10, "images/azul10.png", {
      azul: [0, 0]
    });
    Crafty.sprite(10, 10, "images/vermelho10.png", {
      vermelho: [0, 0]
    });
    Crafty.c("Tela", {
      init: function() {
        this.requires("2D, Canvas, Mouse");
        return this.attr({
          x: 0,
          y: 0,
          w: width,
          h: height,
          blocos: []
        });
      }
    });
    Crafty.c("Verde", {
      init: function() {
        this.requires("2D, Canvas, Collision, verde, WiredHitBox");
        this.attr({
          w: 150,
          h: 150,
          rotation: 1
        });
        this.addComponent('verde').origin("center");
        return this.collision(new Crafty.polygon([[150.0, 75.0], [147.44443697168012, 94.411428382689053], [139.9519052838329, 112.5], [128.03300858899107, 128.03300858899107], [112.5, 139.9519052838329], [94.411428382689067, 147.44443697168012], [75.0, 150.0], [55.588571617310954, 147.44443697168012], [37.500000000000014, 139.9519052838329], [21.966991411008941, 128.03300858899107], [10.048094716167114, 112.50000000000003], [2.5555630283198809, 94.411428382689081], [0.0, 75.000000000000014], [2.5555630283198667, 55.588571617310976], [10.048094716167085, 37.500000000000021], [21.966991411008905, 21.966991411008962], [37.499999999999964, 10.048094716167128], [55.58857161731089, 2.5555630283198951], [74.999999999999986, 0.0], [94.411428382689024, 2.5555630283198667], [112.49999999999994, 10.048094716167071], [128.03300858899104, 21.966991411008927], [139.95190528383287, 37.499999999999964], [147.44443697168009, 55.588571617310883], [150.0, 74.999999999999986]]));
      }
    });
    Crafty.c("bloco", {
      init: function() {
        this.requires("2D, Canvas, Collision, Color");
        this.attr({
          w: 1,
          h: 1
        });
        this.color("#000");
        this.bind("EnterFrame", function() {
          this.x += this.v.x;
          this.y += this.v.y;
          if ((this.x > width && this.y < cy) || (this.x < 0 && this.y < cy)) {
            resultados.push(Crafty.e("2D, Canvas, Color").attr({
              x: this.ponto[0],
              y: this.ponto[1],
              w: 3,
              h: 3
            }).color("#f00"));
          } else if ((this.x > width && this.y >= cy) || (this.x < 0 && this.y >= cy)) {
            resultados.push(Crafty.e("2D, Canvas, Color").attr({
              x: this.ponto[0],
              y: this.ponto[1],
              w: 3,
              h: 3
            }).color("#00f"));
          }
          if (this.x > width + 5 || this.x < 0 - 5 || this.y > height + 5 || this.y < 0 - 5) {
            return this.destroy();
          }
        });
        this.onHit("verde1", function() {
          var novoX, novoY, theta;
          theta = this.v.angleBetween(new Crafty.math.Vector2D(this.x - verde1.x - r, this.y - verde1.y - r));
          novoX = -1 * (this.v.x * Math.cos(2 * theta) - this.v.y * Math.sin(2 * theta));
          novoY = -1 * (this.v.x * Math.sin(2 * theta) + this.v.y * Math.cos(2 * theta));
          return this.v.setValues(novoX, novoY);
        });
        this.onHit("verde2", function() {
          var novoX, novoY, theta;
          theta = this.v.angleBetween(new Crafty.math.Vector2D(this.x - verde2.x - r, this.y - verde2.y - r));
          novoX = -1 * (this.v.x * Math.cos(2 * theta) - this.v.y * Math.sin(2 * theta));
          novoY = -1 * (this.v.x * Math.sin(2 * theta) + this.v.y * Math.cos(2 * theta));
          return this.v.setValues(novoX, novoY);
        });
        return this.onHit("verde3", function() {
          var novoX, novoY, theta;
          theta = this.v.angleBetween(new Crafty.math.Vector2D(this.x - verde3.x - r, this.y - verde3.y - r));
          novoX = -1 * (this.v.x * Math.cos(2 * theta) - this.v.y * Math.sin(2 * theta));
          novoY = -1 * (this.v.x * Math.sin(2 * theta) + this.v.y * Math.cos(2 * theta));
          return this.v.setValues(novoX, novoY);
        });
      }
    });
    window.tela = Crafty.e("Tela");
    verde1 = Crafty.e("Verde, verde1, Collision").attr({
      x: posverde1[0],
      y: posverde1[1],
      i: 0
    });
    verde2 = Crafty.e("Verde, verde2, Collision").attr({
      x: posverde2[0],
      y: posverde2[1],
      i: 0
    });
    verde3 = Crafty.e("Verde, verde3, Collision").attr({
      x: posverde3[0],
      y: posverde3[1],
      i: 0
    });
    window.geraBlocos();
    return window.reset = function() {
      var _k, _l, _len, _len1, _results;
      for (_k = 0, _len = blocos.length; _k < _len; _k++) {
        i = blocos[_k];
        i.destroy();
      }
      _results = [];
      for (_l = 0, _len1 = resultados.length; _l < _len1; _l++) {
        i = resultados[_l];
        _results.push(i.destroy());
      }
      return _results;
    };
  };

}).call(this);
