// Generated by CoffeeScript 1.6.1
var bifurcacao, mapa;

mapa = function(a, x) {
  return a * x * (1 - x);
};

bifurcacao = function() {
  var A, a, amax, amin, data, graph, i, it, pontos, x, x0, _fn, _i, _len;
  it = 100;
  amin = parseFloat(document.getElementById("amin").value);
  amax = parseFloat(document.getElementById("amax").value);
  x0 = 0.12345;
  if (amin < 1) {
    alert("amin precisa ser maior ou igual a 1");
    return 0;
  }
  A = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; _i <= 100; i = ++_i) {
      _results.push(((amax - amin) * (i / 100)) + amin);
    }
    return _results;
  })();
  pontos = [];
  data = [
    {
      data: pontos,
      label: "a",
      points: {
        show: true
      }
    }
  ];
  x = x0;
  _fn = function(a) {
    var j, _fn1, _j, _k, _results;
    _fn1 = function(i) {
      return x = mapa(a, x);
    };
    for (i = _j = 0; 0 <= it ? _j < it : _j > it; i = 0 <= it ? ++_j : --_j) {
      _fn1(i);
    }
    _results = [];
    for (j = _k = 0; 0 <= it ? _k < it : _k > it; j = 0 <= it ? ++_k : --_k) {
      _results.push((function(j) {
        x = mapa(a, x);
        return pontos.push([a, x]);
      })(j));
    }
    return _results;
  };
  for (_i = 0, _len = A.length; _i < _len; _i++) {
    a = A[_i];
    _fn(a);
  }
  return graph = Flotr.draw(container, data, {
    yaxis: {
      max: 1,
      min: 0
    },
    xaxis: {
      max: amax,
      min: amin
    }
  });
};

bifurcacao();
