// Generated by CoffeeScript 1.6.1
var cobweb, container, mapa;

container = document.getElementById('container');

mapa = function(x) {
  if ((0 < x && x < 1)) {
    return 4 * x * (1 - x);
  } else {
    return alert('Coloque um número entre 0 e 1 e recarregue a página');
  }
};

cobweb = function() {
  var dados1, dados2, data, graph, i, x, y, _fn, _i;
  dados1 = [];
  dados2 = [];
  x = parseFloat(document.getElementById('x0').value);
  y = parseFloat(document.getElementById('y0').value);
  data = [
    {
      data: dados1,
      label: 'x0=' + x.toString()
    }, {
      data: dados2,
      label: 'y0=' + y.toString()
    }
  ];
  _fn = function(i) {
    dados1.push([i, mapa(x)]);
    dados2.push([i, mapa(y)]);
    y = mapa(y);
    return x = mapa(x);
  };
  for (i = _i = 0; _i <= 100; i = ++_i) {
    _fn(i);
  }
  document.getElementById('x0').innerHTML = "x0 = " + x0;
  document.getElementById('y0').innerHTML = "y0 = " + y0;
  return graph = Flotr.draw(container, data, {
    yaxis: {
      max: 1,
      min: 0
    },
    legend: {
      position: 'se'
    },
    HtmlText: false
  });
};

cobweb();
